### PR TITLE
Fix tests and Travis pipeline

### PR DESCRIPTION
**Pull request by matks**

### CODE REVIEW

**Comment by matks** [comment]
Travis build failed because of outdated security check
```
3.21s$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 95 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.3.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/inflector (v1.3.0): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (2.1.4): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing symfony/polyfill-ctype (v1.8.0): Loading from cache
  - Installing symfony/yaml (v3.4.11): Loading from cache
  - Installing incenteev/composer-parameter-handler (v2.1.3): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing php-http/promise (v1.0.0): Loading from cache
  - Installing php-http/httplug (v1.1.0): Loading from cache
  - Installing php-http/discovery (1.4.0): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
  - Installing php-http/guzzle6-adapter (v1.1.1): Loading from cache
  - Installing symfony/options-resolver (v3.4.11): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing clue/stream-filter (v1.4.0): Loading from cache
  - Installing php-http/message (1.6.0): Loading from cache
  - Installing php-http/client-common (1.7.0): Loading from cache
  - Installing php-http/cache-plugin (v1.5.0): Loading from cache
  - Installing knplabs/github-api (2.8.0): Loading from cache
  - Installing lp-digital/github-event-parser (v0.8.3): Loading from cache
  - Installing paragonie/random_compat (v2.0.15): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing symfony/process (v3.4.11): Loading from cache
  - Installing symfony/polyfill-php70 (v1.8.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.8.0): Loading from cache
  - Installing symfony/http-foundation (v3.4.11): Loading from cache
  - Installing symfony/event-dispatcher (v3.4.11): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.4.11): Loading from cache
  - Installing symfony/http-kernel (v3.4.11): Loading from cache
  - Installing symfony/filesystem (v3.4.11): Loading from cache
  - Installing symfony/dependency-injection (v3.4.11): Loading from cache
  - Installing symfony/config (v3.4.11): Loading from cache
  - Installing symfony/class-loader (v3.4.11): Loading from cache
  - Installing symfony/console (v3.4.11): Loading from cache
  - Installing composer/ca-bundle (1.1.1): Loading from cache
  - Installing sensiolabs/security-checker (v4.1.8): Loading from cache
  - Installing sensio/distribution-bundle (v5.0.22): Loading from cache
  - Installing symfony/routing (v3.4.11): Loading from cache
  - Installing symfony/finder (v3.4.11): Loading from cache
  - Installing symfony/polyfill-apcu (v1.8.0): Loading from cache
  - Installing symfony/cache (v3.4.11): Loading from cache
  - Installing symfony/framework-bundle (v3.4.11): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing sensio/framework-extra-bundle (v3.0.29): Loading from cache
  - Installing symfony/asset (v3.4.11): Loading from cache
  - Installing symfony/var-dumper (v3.4.11): Loading from cache
  - Installing twig/twig (v2.4.8): Loading from cache
  - Installing symfony/twig-bridge (v3.4.11): Loading from cache
  - Installing symfony/debug-bundle (v3.4.11): Loading from cache
  - Installing symfony/lts (v3)
  - Installing monolog/monolog (1.23.0): Loading from cache
  - Installing symfony/monolog-bridge (v3.4.11): Loading from cache
  - Installing symfony/monolog-bundle (v3.3.0): Loading from cache
  - Installing symfony/polyfill-util (v1.8.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.8.0): Loading from cache
  - Installing symfony/inflector (v3.4.11): Loading from cache
  - Installing symfony/property-access (v3.4.11): Loading from cache
  - Installing symfony/security (v3.4.11): Loading from cache
  - Installing symfony/security-bundle (v3.4.11): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.0.2): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.2.2): Loading from cache
  - Installing symfony/templating (v3.4.11): Loading from cache
  - Installing symfony/twig-bundle (v3.4.11): Loading from cache
  - Installing symfony/translation (v3.4.11): Loading from cache
  - Installing symfony/validator (v3.4.11): Loading from cache
  - Installing symfony/web-profiler-bundle (v3.4.11): Loading from cache
  - Installing symfony/stopwatch (v3.4.11): Loading from cache
  - Installing symfony/polyfill-php72 (v1.8.0): Loading from cache
  - Installing php-cs-fixer/diff (v1.3.0): Loading from cache
  - Installing composer/xdebug-handler (1.1.0): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing friendsofphp/php-cs-fixer (v2.12.1): Loading from cache
  - Installing nette/utils (v2.5.2): Loading from cache
  - Installing nette/finder (v2.4.2): Loading from cache
  - Installing nette/neon (v2.4.3): Loading from cache
  - Installing nette/php-generator (v3.0.4): Loading from cache
  - Installing phpstan/phpdoc-parser (0.3): Loading from cache
  - Installing nikic/php-parser (v4.0.2): Loading from cache
  - Installing nette/robot-loader (v3.0.4): Loading from cache
  - Installing nette/di (v2.4.13): Loading from cache
  - Installing nette/bootstrap (v2.4.6): Loading from cache
  - Installing jean85/pretty-package-versions (1.2): Loading from cache
  - Installing phpstan/phpstan (0.10.1): Loading from cache
  - Installing symfony/dom-crawler (v3.4.11): Loading from cache
  - Installing symfony/browser-kit (v3.4.11): Loading from cache
  - Installing symfony/phpunit-bridge (v3.4.25): Loading from cache
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
php-http/discovery suggests installing puli/composer-plugin (Sets up Puli which is recommended for Discovery to work. Check http://docs.php-http.org/en/latest/discovery.html for more details.)
php-http/message suggests installing slim/slim (Used with Slim Framework PSR-7 implementation)
php-http/message suggests installing zendframework/zend-diactoros (Used with Diactoros Factories)
php-http/client-common suggests installing php-http/logger-plugin (PSR-3 Logger plugin)
php-http/client-common suggests installing php-http/stopwatch-plugin (Symfony Stopwatch plugin)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
symfony/console suggests installing symfony/lock
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/framework-bundle suggests installing ext-apcu (For best performance of the system caches)
symfony/framework-bundle suggests installing symfony/form (For using forms)
symfony/framework-bundle suggests installing symfony/property-info (For using the property_info service)
symfony/framework-bundle suggests installing symfony/serializer (For using the serializer service)
symfony/framework-bundle suggests installing symfony/web-link (For using web links, features such as preloading, prefetching or prerendering)
sensio/framework-extra-bundle suggests installing symfony/expression-language
sensio/framework-extra-bundle suggests installing symfony/psr-http-message-bridge (To use the PSR-7 converters)
symfony/var-dumper suggests installing ext-symfony_debug
symfony/twig-bridge suggests installing symfony/expression-language (For using the ExpressionExtension)
symfony/twig-bridge suggests installing symfony/form (For using the FormExtension)
symfony/twig-bridge suggests installing symfony/web-link (For using the WebLinkExtension)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
symfony/security suggests installing symfony/expression-language (For using the expression voter)
symfony/security suggests installing symfony/form
symfony/security suggests installing symfony/ldap (For using the LDAP user and authentication providers)
symfony/security-bundle suggests installing symfony/security-acl (For using the ACL functionality of this bundle)
symfony/validator suggests installing symfony/expression-language (For using the Expression validator)
symfony/validator suggests installing symfony/intl
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-isidenticalstring (For IsIdenticalString constraint.)
friendsofphp/php-cs-fixer suggests installing php-cs-fixer/phpunit-constraint-xmlmatchesxsd (For XmlMatchesXsd constraint.)
nette/bootstrap suggests installing tracy/tracy (to use Configurator::enableTracy())
symfony/dom-crawler suggests installing symfony/css-selector
Package symfony/lts is abandoned, you should avoid using it. Use symfony/flex instead.
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
 // Clearing the cache for the dev environment with debug                       
 // true                                                                        
                                                                                
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
                                                                                
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
 Trying to install assets as relative symbolic links.
                                                                                
 [OK] No assets were provided by any bundle.                                    
                                                                                
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
before_install.3
13.36s$ ./vendor/bin/simple-phpunit install
Installing phpunit/phpunit (6.5.14)
Plugins have been disabled.
  - Installing phpunit/phpunit (6.5.14): Loading from cache
Created project in phpunit-6.5
symfony/yaml is not required in your composer.json and has not been removed
composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Package operations: 23 installs, 0 updates, 0 removals
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing theseer/tokenizer (1.1.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing phpunit/php-code-coverage (5.3.2): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing doctrine/instantiator (1.0.5): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.10): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.3): Loading from cache
  - Installing symfony/phpunit-bridge (6.5.99): Symlinking from /home/travis/build/PrestaShop/prestonbot/vendor/symfony/phpunit-bridge
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating optimized autoload files
0.21s$ ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
                                                                       
  An error occurred: Could not resolve host: security.sensiolabs.org.  
                                                                       
The command "./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock" exited with 1.
```

**Comment by matks** [comment]
@mickaelandrieu In order to comply with Sensio Security Checkers requiremens, I decided to perform a global update of dependencies in https://github.com/PrestaShop/prestonbot/pull/82/commits/66816f855002f6dfedbe87a9deeb8f0febdb1185

Tests pass locally, so I think it should be fine 👍

**Comment by matks** [comment]
Now tests on travis because `Environment variable not found: "GH_TOKEN"`. You're right @mickaelandrieu, the dev who did all this [is really a noob](https://github.com/PrestaShop/prestonbot/pull/79#issuecomment-483678785) !

**Comment by matks** [comment]
So Travis has decided to remove environment variables: `Encrypted environment variables have been removed for security reasons`.

OK, it seems they have very valid security reasons for that. But I have no idea what easy replacement I can use 😛. Looks like I might need to modify prestonbot deeper in order to fix CI.

I think I should aim for a API-free unit test suite. Booting an API Client should not be mandatory for unit tests, and this would remove the need for a GH_TOKEN. But this is a bigger work than expected...

**Comment by matks** [comment]
I only wanted to [stop the wording label spam](https://github.com/PrestaShop/prestonbot/pull/79) 😢 ...

**Comment by PierreRambaud** [comment]
They remove encrypted variables, but you're still able to set up variables in repository Settings (travis) 
image

**Comment by matks** [comment]
So there was env variables GH_TOKEN and GH_SECURED_TOKEN to be used in https://github.com/PrestaShop/prestonbot/blob/master/app/config/parameters.yml.dist#L16 but since they were created as encrypted env variables, they were disabled.

I replaced them with a dummy set as prestonbot unit tests requires these 2 env variables to be defined, but not valid. Got a green build 😄 ✅

**Pull request merged**
