### PR TITLE
Do not add Waiting for wording when already validated & fix PR validation comment being wrongly removed

### PR DESCRIPTION
**Pull request by atomiix**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | When every translation string have been validated, do not add the label "Waiting for wording". Also, the comment describing what was wrong on the PR description table was removed when editing a PR even if the PR was not linked to an issue. This PR fixes it.
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| How to test?  | Tests must pass

### CODE REVIEW

**Review by matks — APPROVED** [review]
Hi, so the label "WORDING_APPROVED" will now be added automatically when all strings are validated, and Wording team should not add it manually anymore, is that right ?

**Comment by atomiix** [comment]
@matks no, the label WORDING_APPROVED should still be added manually but the label WAITING_FOR_WORDING will now be added only if **not** all the new wordings have been approved. And when we add WAITING_FOR_WORDING we remove WORDING_APPROVED at the same time (which wasn't the case until now).

**Comment by matks** [comment]
> @matks no, the label WORDING_APPROVED should still be added manually but the label WAITING_FOR_WORDING will now be added only if **not** all the new wordings have been approved. And when we add WAITING_FOR_WORDING we remove WORDING_APPROVED at the same time (which wasn't the case until now).

What happens if
- a new PR is submitted
- so it's marked as "Waiting for wording"
- I start looking at the PR, I see it's good, I add the "Wording approved" label without approving all new wordings
- I remove "Waiting for wording"

On next PR event, will the "Waiting for wording" label be added again ?

**Comment by atomiix** [comment]
@matks Yes!

**Comment by matks** [comment]
> @matks Yes!

Isn't it an issue 😅 ?

For example on a "merge 177x into develop" PR there might be hundred of new wordings. Maybe Wording reviewer wants to skip the wordings validation and just mark the label ?

Ah but I see it comes into conflict with "PR is updated, need to check new wordings added in new commits" 😭 

Well let's leave it like this.

**Review by matthieu-rolland — APPROVED** [review]

**Pull request merged**
